cloudfuse-io/lambdatization

.editorconfig, .github/workflows/style-check.yaml, .markdownlint.yaml, .yamllint.yaml, README.md, infra/common/env/conf.tf, infra/spark/main.tf
Add badges to provide a nicer README experience
NA
=> Badges on README

cli/core.py, cli/plugins/spark.py, infra/core/main.tf, infra/spark/main.tf, infra/spark/terragrunt.hcl
Using the public bucket to get the data seems to create a lot of compatibility issues with SDKs. This PR creates a private copy with a subset of the public NYC dataset copied to it.
NA
=> Use private bucket for test datasets

README.md, cli/plugins/dremio.py, infra/dremio/.terraform.lock.hcl, infra/dremio/build/Dockerfile, infra/dremio/build/README.md, infra/dremio/build/docker-compose.yaml, infra/dremio/build/dremio-env, infra/dremio/build/dremio.conf, infra/dremio/build/lambda-handler.py, infra/dremio/main.tf, infra/dremio/terragrunt.hcl, infra/spark/build/lambda-handler.py
Closes #10
TODO:
The lambda handler is using the REST API to setup the handler.
=> Dremio in lambda

.github/workflows/l12n.yaml, cli/common.py, cli/core.py, cli/plugins/dremio.py, cli/plugins/spark.py, infra/dremio/build/docker-compose.yaml, infra/dremio/build/lambda-handler.py, infra/spark/build/docker-compose.yaml, infra/spark/build/lambda-handler.py
Add the possibility to run the lambdatizated images locally with `l12n dockerized -e engine_name`
Try running from within the `l12n-shell`:
```
l12n dockerized -e spark
l12n dockerized -e dremio
```
=> Run images locally and test builds in CI

README.md
Add some documentation to help getting started
Try out the commands in the docs
=> Describe basic CMDs and configs

.github/workflows/l12n.yaml, cli/plugins/databend.py, infra/databend/.terraform.lock.hcl, infra/databend/build/Dockerfile, infra/databend/build/README.md, infra/databend/build/bootstrap.sh, infra/databend/build/databend-meta.toml, infra/databend/build/databend-query.toml, infra/databend/build/docker-compose.yaml, infra/databend/build/lambda-handler.py, infra/databend/main.tf, infra/databend/terragrunt.hcl
=> Databend lambda

cli/common.py, cli/core.py
* add raise on other `ClientError` messages
* clean unused resource code
=> Error handling

cli/main.py, cli/plugins/dask.py, cli/plugins/monitoring.py, cli/plugins/spark.py, infra/runtime/dask/.terraform.lock.hcl, infra/runtime/dask/build/Dockerfile, infra/runtime/dask/build/README.md, infra/runtime/dask/build/docker-compose.yaml, infra/runtime/dask/build/lambda-handler.py, infra/runtime/dask/main.tf, infra/runtime/dask/terragrunt.hcl
Closes #23 
Add Dask to the list of lambdatized engines
2 minor changes that should be part of https://github.com/cloudfuse-io/lambdatization/pull/31 but I didn't have the time to do the checkout/rebase routine:
- typo in cli/main.py
- autoprint in cli/plugin/spark.py
Apart from that, the rest is typical engine integration
=> Feat(Dask): first version

cli/plugins/spark.py, infra/runtime/spark/build/Dockerfile, infra/runtime/spark/build/lambda-handler.py
=> Imp(spark): reuse the sql cli

infra/runtime/dask/build/lambda-handler.py, infra/runtime/databend/build/lambda-handler.py, infra/runtime/dremio/build/lambda-handler.py, infra/runtime/spark/build/lambda-handler.py
=> Fix(engines): dockerized broken

.github/workflows/trino.yaml
=> CI(trino): fix workdir

.github/workflows/hadoop.yaml
=> Feat(ci): hadoop mirroring

.github/workflows/l12n.yaml
Try increasing CI speed with parallization
=> imp(ci): make image builds parallel

.github/workflows/l12n.yaml, README.md
Add missing engines to CI + docs improvement
=> Fix(ci): missing engines

README.md
=> Fix(doc): broken link

README.md
=> Imp: improve main readme

.github/workflows/ballista.yaml
=> Feat(CI): add ballista build

.github/workflows/ballista.yaml, .github/workflows/semantic-pr.yaml
=> fix: ballista CI

README.md
=> docs: specify types for PR titles

cli/plugins/monitoring.py
=> fix(monitoring): empty error message

.github/workflows/clickhouse.yaml
=> ci(clickhouse): build ci init

.github/gh-runner-setup.sh, .github/workflows/clickhouse.yaml
=> ci(clickhouse): fix build

.github/workflows/clickhouse.yaml, .github/workflows/l12n.yaml, infra/runtime/clickhouse/build/Dockerfile
=> ci: fix image tags

cli/core.py, cli/plugins/monitoring.py, cli/plugins/scaling.py, docs/scaling_metrics.md, docs/standalone_engine_metrics.md, infra/monitoring/bigquery/main.tf, infra/runtime/scaling/.terraform.lock.hcl, infra/runtime/scaling/build/Dockerfile, infra/runtime/scaling/build/docker-compose.yaml, infra/runtime/scaling/build/lambda-handler.py, infra/runtime/scaling/main.tf, infra/runtime/scaling/terragrunt.hcl
Create a new dashboard that shows scaling performances of AWS Lambda with docker images
=> feat(monitoring): add scaling infra and dashboard

.github/workflows/engines.yaml, .github/workflows/l12n.yaml, l12n-shell
Better use of cache for CI builds
=> ci: improve speed

README.md
=> fix: broken badge

.github/workflows/engines.yaml, .github/workflows/shell.yaml, .gitignore, README.md, cli/common.py, cli/core.py, cli/plugins/monitoring.py, docker/cli/entrypoint.sh, infra/monitoring/terragrunt.local.hcl, infra/runtime/terragrunt.local.hcl, l12n, l12n-shell
The goal of this PR is to enable multiple instances of the terraform stack.
=> feat: enable multiple deployments

docker/clickhouse/README.md, docker/clickhouse/config.xml, docker/clickhouse/lambda-handler.py
=> fix(clickhouse): bad write paths

cli/plugins/monitoring.py, cli/plugins/tfcloud.py, infra/monitoring/bigquery/.terraform.lock.hcl, infra/monitoring/bigquery/main.tf, infra/runtime/lambdacli/main.tf, infra/terragrunt.cloud.hcl, infra/terragrunt.local.hcl
=> fix: monitoring deployment from tfcloud

README.md, cli/common.py, cli/core.py, cli/plugins/clickhouse.py, cli/plugins/monitoring.py, cli/plugins/scaling.py, cli/plugins/scheduling.py, infra/monitoring/bigquery/engine_durations.json, infra/monitoring/bigquery/main.tf, infra/monitoring/bigquery/scaling_durations.json, infra/runtime/lambdacli/main.tf, infra/terragrunt.cloud.hcl, infra/terragrunt.local.hcl
Add region and revision as context for metrics
=> feat: new context fields

README.md, cli/common.py, cli/main.py, cli/plugins/lambdacli.py, cli/plugins/monitoring.py, cli/plugins/scaling.py, cli/requirements.txt, docker/scaling/docker-compose.yaml, docs/scaling_metrics.md, infra/monitoring/bigquery/engine_durations.json, infra/monitoring/bigquery/scaling_durations.json, infra/runtime/lambdacli/main.tf, infra/runtime/scaling/terragrunt.hcl, infra/runtime/scheduler/main.tf, infra/terragrunt.cloud.hcl, infra/terragrunt.local.hcl
Added scheduler for scaling benchmark
Changed `multiprocessing` for `asyncio` when running scaling benchmark for better performance and compatibility with Lambda
=> fix: scaling benchmark various shortcommings

cli/plugins/monitoring.py
=> fix: unexpected none with lambda error

cli/plugins/monitoring.py
=> fix: typo in p99 duration

infra/runtime/scheduler/main.tf
=> fix: undesired update of tf lock files

README.md
=> fix: switch for iframed dashboard links

chappy/examples/Cargo.toml, chappy/examples/n_to_n.rs, chappy/interceptor/src/bindings.rs, chappy/interceptor/src/conf.rs, chappy/interceptor/src/utils.rs, cli/plugins/chappy.py, docker/ballista/distributed-handler.py, docker/chappy/dev-handler.py, docker/trino/Dockerfile
We want to validate that the hole punching is behaving well when a cluster of nodes is communicating.
=> test(Chappy): add cluster tests

chappy/Cargo.lock, chappy/Cargo.toml, chappy/examples/n_to_n.rs, chappy/interceptor/src/bindings.rs, chappy/interceptor/src/utils.rs, chappy/perforator/Cargo.toml, chappy/perforator/src/binding_service.rs, chappy/perforator/src/conf.rs, chappy/perforator/src/forwarder.rs, chappy/perforator/src/main.rs, chappy/perforator/src/perforator.rs, chappy/perforator/src/quic_utils.rs, chappy/perforator/src/shutdown.rs, chappy/perforator/src/udp_utils.rs, chappy/seed/build.rs, chappy/seed/src/seed_service.rs, chappy/util/src/lib.rs, cli/core.py, cli/plugins/ballista.py, cli/plugins/chappy.py, docker/ballista/distributed-handler.py
This PR contains many improvements. Unfortunately stability is still not good enough.
=> perf: single quic endpoint

chappy/Cargo.lock, chappy/Cargo.toml, chappy/examples/n_to_n.rs, chappy/interceptor/Cargo.toml, chappy/interceptor/src/bindings.rs, chappy/interceptor/src/utils.rs, chappy/perforator/src/binding_service.rs, chappy/perforator/src/conf.rs, chappy/perforator/src/lib.rs, chappy/perforator/src/main.rs, chappy/perforator/src/perforator.rs, chappy/seed/Cargo.toml, chappy/seed/seed.proto, chappy/seed/src/cluster_manager/manager.rs, chappy/seed/src/cluster_manager/message.rs, chappy/seed/src/cluster_manager/mod.rs, chappy/seed/src/cluster_manager/state.rs, chappy/seed/src/cluster_manager/summary.rs, chappy/seed/src/lib.rs, chappy/seed/src/main.rs, chappy/seed/src/seed_service.rs, chappy/util/src/awaitable_map.rs, chappy/util/src/lib.rs, chappy/util/src/protocol.rs, cli/plugins/ballista.py, cli/plugins/chappy.py
=> feat(seed): track cluster state

.github/workflows/chappy.yaml
=> ci(chappy): clippy and tests

chappy/Cargo.lock, chappy/Cargo.toml, chappy/seed/Cargo.toml, chappy/seed/src/address_stream.rs, chappy/seed/src/cluster_manager/manager.rs, chappy/seed/src/cluster_manager/state.rs, chappy/seed/src/cluster_manager/summary.rs, chappy/seed/src/lib.rs, chappy/seed/src/registered_endpoints.rs, chappy/seed/src/seed_service.rs
=> refactor(seed): address stream and registered endpoints

chappy/Cargo.lock, chappy/examples/n_to_n.rs, chappy/examples/server.rs, chappy/interceptor/src/bindings.rs, chappy/interceptor/src/lib.rs, chappy/interceptor/src/utils.rs, chappy/perforator/src/forwarder.rs, chappy/perforator/src/main.rs, chappy/perforator/src/perforator.rs, chappy/util/src/protocol.rs, docker/ballista/distributed-handler.py
=> refactor: remove unnecessary bind binding

cli/plugins/ballista.py, docker/ballista/standalone-handler.py
=> fix: ballista timing out because of debug logging

infra/runtime/scheduler/main.tf
=> ci: decrease schedule
